/**
 * Product, quality, and engineering actions owned by this package.
 *
 * Handler-free entries are deliberate ontology-only lifecycle transitions. Document import
 * actions that require object-store/parser atoms are owned by `@kf/documents`, not by this
 * always-loaded package.
 */
export const PRODUCT_QUALITY_ACTION_IDS = [
  'promote_configuration_item',
  'supersede_configuration_item',
  'retire_configuration_item',
  'publish_interface_contract',
  'deprecate_interface_contract',
  'withdraw_interface_contract',
  'record_physical_binding',
  'remove_physical_binding',
  'submit_document_for_review',
  'approve_controlled_document',
  'make_document_effective',
  'supersede_controlled_document',
  'withdraw_controlled_document',
  'raise_nonconformity',
  'contain_nonconformity',
  'investigate_nonconformity',
  'disposition_nonconformity',
  'close_nonconformity',
  'open_capa',
  'approve_capa_plan',
  'implement_capa',
  'check_capa_effectiveness',
  'close_capa',
  'register_supplier',
  'qualify_supplier',
  'restrict_supplier',
  'disqualify_supplier',
  'register_equipment',
  'place_equipment_in_service',
  'remove_equipment_from_service',
  'quarantine_equipment',
  'retire_equipment',
  'receive_complaint',
  'triage_complaint',
  'investigate_complaint',
  'close_complaint',
  'propose_risk_control',
  'implement_risk_control',
  'verify_risk_control',
  'retire_risk_control',
  'define_test',
  'approve_test_definition',
  'supersede_test_definition',
  'plan_test_execution',
  'execute_test',
  'record_test_result',
  'invalidate_test_execution',
] as const;
