-- migrate:up

-- The agent at home (ADR 0040 decisions 7, 8 and 9; SAS §24B, KF-SAS-RQ-271, RQ-272, RQ-274;
-- milestone M4, KF-WAR-0006; closes the database half of §100.51 and §100.52).
--
-- The in-app agent and the notifications need three things from the database, and nothing else:
--
--   1. WHICH MODEL MAY READ WHAT, per organization: `core.model_routing_policy`. One column that
--      matters, `provider_ceiling`: the highest classification of content that may leave the host,
--      to a provider's model or in a notification. `none`, `public` or `internal`, and never
--      `confidential` or `restricted` — the database refuses those in every session, an
--      administrator's included (KF-ROUTE-001), because ADR 0040 decision 8 is not a default an
--      organization may change: confidential and restricted content is answered on the host or
--      not at all. No row means `internal`, ADR 0040's default; whether any provider is reachable
--      at all is the deployment's (a key, or none). Written only by `set_model_routing_policy`
--      (KF-ROUTE-002), which is institutional, so no agent can widen what reaches a provider.
--      Append-only; the highest revision per organization is in force.
--
--   2. A PERSON'S OWN NOTIFICATION SETTING: `core.notification_preference`, per person and
--      organization: the daily digest `daily` (also what no row means) or `off`, and the urgent
--      push `urgent` (no row) or `off`. Quiet by default is the shape, not a setting: nothing but
--      an urgent item is ever pushed. Written only by `set_notification_preference`, for the
--      person who performs it and never by an agent acting for them (KF-NOTIFY-001, KF-NOTIFY-002).
--
--   3. WHAT A NOTIFICATION MAY SAY, decided here: `core.needs_you_digest()` and
--      `core.urgent_notifications(since)`, security definer, executable by `kf_notifier` alone.
--      The notifier login reads no table. It receives, per person, the items Needs you would list
--      for them (the same three lists, the same read grants and clearance), and for each item a
--      title and identifier ONLY when the item's classification is at or below its organization's
--      provider ceiling; everything else arrives as a row with no title and no identifier, which
--      the digest renders as a count and a link (KF-SAS-RQ-274). The urgent function returns no
--      title at all: a push says that something needs the person, and nothing about what.
--
-- THE GUARDS THIS INHERITS. Both new tables: row security enabled and forced, every policy's
-- context function wrapped as `(select …)`, the act write guard (core.install_action_context_guards),
-- a kf_backup read policy, an export section, and a declared exemption from the master-record input
-- triggers. Neither is transient (§64B): a routing decision and a person's notification setting are
-- records of decisions, exported and restored. The chat keeps nothing (KF-WAR-0006; ADR 0040): no
-- table here holds a question or an answer.

-- 0. The notifier's group role --------------------------------------------------------------------

do $$
begin
  if not exists (select from pg_roles where rolname = 'kf_notifier') then
    create role kf_notifier nologin;
  end if;
end
$$;

comment on role kf_notifier is
  'kf-notify''s login inherits this and nothing else: execute on core.needs_you_digest() and '
  'core.urgent_notifications(timestamptz). It reads no table; what a notification may say is '
  'decided by those functions (KF-SAS-RQ-274).';

grant usage on schema core to kf_notifier;

-- 1. Which model may read what --------------------------------------------------------------------

create table core.model_routing_policy (
  id               uuid primary key default uuidv7(),
  revision         bigint generated by default as identity unique,
  organization_id  uuid not null references org.organization (id) on delete restrict,
  -- The highest classification that may leave the host: to a provider's model, or in a
  -- notification. Never confidential or restricted (KF-ROUTE-001, and this check again).
  provider_ceiling text not null check (provider_ceiling in ('none', 'public', 'internal')),
  reason           text not null check (length(btrim(reason)) >= 8),
  set_by           uuid not null references org.person (id),
  set_by_action    uuid not null unique references core.action (id) on delete restrict,
  set_at           timestamptz not null default now()
);

create index model_routing_policy_key on core.model_routing_policy (organization_id, revision desc);

comment on table core.model_routing_policy is
  'The highest classification of content that may leave the host, to a provider''s model or in a '
  'notification, per organization (ADR 0040 decision 8, KF-SAS-RQ-271, RQ-274). none, public or '
  'internal; never confidential or restricted (KF-ROUTE-001). No row means internal. Append-only; '
  'the highest revision is in force. Written only by set_model_routing_policy, an institutional act.';

-- What is in force for one organization: its latest row, else the default. Definer, so the
-- notifier's functions and every reader ask one question with one answer.
create function core.provider_ceiling_in_force(p_organization uuid) returns text
language sql
stable
security definer
set search_path = pg_catalog, core
as $$
  select coalesce(
    (select p.provider_ceiling from core.model_routing_policy p
      where p.organization_id = p_organization
      order by p.revision desc limit 1),
    'internal')
$$;

revoke all on function core.provider_ceiling_in_force(uuid) from public;
grant execute on function core.provider_ceiling_in_force(uuid) to kf_app;

create function core.model_routing_policy_bounded() returns trigger
language plpgsql
security definer
set search_path = pg_catalog, core
as $$
begin
  if tg_op <> 'INSERT' then
    raise exception 'a model routing policy is superseded by a later one, never % (Law 6)', lower(tg_op)
      using errcode = 'insufficient_privilege';
  end if;
  -- In every session, an administrator's and a restore's included: ADR 0040 decision 8 is not an
  -- organization's to change.
  if new.provider_ceiling in ('confidential', 'restricted') then
    raise exception 'KF-ROUTE-001: % content is answered only on the host and never sent to a '
      'provider''s model or in a notification (ADR 0040, KF-SAS-RQ-271)', new.provider_ceiling
      using errcode = 'check_violation';
  end if;
  if core.session_is_administrator() then
    return new;
  end if;
  if core.current_action_type() is distinct from 'set_model_routing_policy' then
    raise exception 'KF-ROUTE-002: a model routing policy is written only by '
      'set_model_routing_policy, an institutional act; this transaction recorded %',
      coalesce(core.current_action_type(), 'no act')
      using errcode = 'check_violation';
  end if;
  new.revision := nextval(pg_get_serial_sequence('core.model_routing_policy', 'revision'));
  new.organization_id := core.current_organization();
  new.set_by := core.current_actor_or_null();
  new.set_by_action := core.current_action_id();
  new.set_at := now();
  return new;
end
$$;

revoke all on function core.model_routing_policy_bounded() from public;

create trigger model_routing_policy_bounded
  before insert or update or delete on core.model_routing_policy
  for each row execute function core.model_routing_policy_bounded();

create trigger model_routing_policy_guard_context
  before insert on core.model_routing_policy
  for each row execute function core.require_transaction_context();

alter table core.model_routing_policy enable row level security;
alter table core.model_routing_policy force row level security;

-- Everyone in the organization may read what may leave it: the answer names its backend, and the
-- reason a question went to the host is not a secret from the person asking.
create policy model_routing_policy_read on core.model_routing_policy
  for select
  using (organization_id = (select core.current_organization()));

create policy model_routing_policy_insert on core.model_routing_policy
  for insert
  with check (
    organization_id = (select core.current_organization())
    and set_by = (select core.current_actor_or_null())
    and set_by_action = (select core.current_action_id())
  );

create policy model_routing_policy_auditor_read on core.model_routing_policy
  for select to kf_auditor using (true);
create policy model_routing_policy_backup_read on core.model_routing_policy
  for select to kf_backup using (true);

revoke all on core.model_routing_policy from public;
grant select, insert on core.model_routing_policy to kf_app;
grant select on core.model_routing_policy to kf_readonly, kf_auditor, kf_backup;
grant select on sequence core.model_routing_policy_revision_seq to kf_backup;

-- 2. A person's own notification setting ---------------------------------------------------------

create table core.notification_preference (
  id               uuid primary key default uuidv7(),
  revision         bigint generated by default as identity unique,
  organization_id  uuid not null references org.organization (id) on delete restrict,
  person_id        uuid not null references org.person (id),
  digest           text not null check (digest in ('daily', 'off')),
  push             text not null check (push in ('urgent', 'off')),
  set_by_action    uuid not null unique references core.action (id) on delete restrict,
  set_at           timestamptz not null default now()
);

create index notification_preference_key
  on core.notification_preference (organization_id, person_id, revision desc);

comment on table core.notification_preference is
  'A person''s own notification setting per organization (ADR 0040 decision 9, KF-SAS-RQ-274): the '
  'daily digest (daily, the default) or off, the urgent push (urgent, the default) or off. Nothing '
  'non-urgent is ever pushed. Append-only; written only by set_notification_preference, for the '
  'person performing it, never by an agent acting for them.';

create function core.notification_preference_bounded() returns trigger
language plpgsql
security definer
set search_path = pg_catalog, core
as $$
begin
  if tg_op <> 'INSERT' then
    raise exception 'a notification preference is superseded by a later one, never % (Law 6)',
      lower(tg_op)
      using errcode = 'insufficient_privilege';
  end if;
  if core.session_is_administrator() then
    return new;
  end if;
  if core.current_agent_or_null() is not null then
    raise exception 'KF-NOTIFY-001: how a person is notified is their own setting; agent % acting '
      'for them may not change it', core.current_agent_or_null()
      using errcode = 'check_violation';
  end if;
  if core.current_action_type() is distinct from 'set_notification_preference' then
    raise exception 'KF-NOTIFY-002: a notification preference is written only by '
      'set_notification_preference; this transaction recorded %',
      coalesce(core.current_action_type(), 'no act')
      using errcode = 'check_violation';
  end if;
  new.revision := nextval(pg_get_serial_sequence('core.notification_preference', 'revision'));
  new.organization_id := core.current_organization();
  -- Whose setting it is: the person performing the act, never a person the caller names.
  new.person_id := core.current_actor_or_null();
  new.set_by_action := core.current_action_id();
  new.set_at := now();
  return new;
end
$$;

revoke all on function core.notification_preference_bounded() from public;

create trigger notification_preference_bounded
  before insert or update or delete on core.notification_preference
  for each row execute function core.notification_preference_bounded();

create trigger notification_preference_guard_context
  before insert on core.notification_preference
  for each row execute function core.require_transaction_context();

alter table core.notification_preference enable row level security;
alter table core.notification_preference force row level security;

create policy notification_preference_read on core.notification_preference
  for select
  using (
    organization_id = (select core.current_organization())
    and person_id = (select core.current_principal_or_null())
  );
create policy notification_preference_insert on core.notification_preference
  for insert
  with check (
    organization_id = (select core.current_organization())
    and person_id = (select core.current_actor_or_null())
    and set_by_action = (select core.current_action_id())
  );
create policy notification_preference_auditor_read on core.notification_preference
  for select to kf_auditor using (true);
create policy notification_preference_backup_read on core.notification_preference
  for select to kf_backup using (true);

revoke all on core.notification_preference from public;
grant select, insert on core.notification_preference to kf_app;
grant select on core.notification_preference to kf_readonly, kf_auditor, kf_backup;
grant select on sequence core.notification_preference_revision_seq to kf_backup;

-- 3. What a notification may say ------------------------------------------------------------------

-- Whether a person may read one record now, as Needs you decides it: a live, unretired clearance in
-- the organization at or above the record's classification, and a live read grant reaching it —
-- organization-wide or on the record, within the grant's ceiling, to the person or to an assignment
-- they hold (enumerateAccessCoverage + coveringGrants in @kf/authorization, applied in SQL).
create function core.notification_person_reads(
  p_person uuid, p_organization uuid, p_object uuid, p_classification text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, core, org, registry
as $$
  with rank as (select c.rank from registry.classification c where c.id = p_classification)
  select exists (
           select 1
             from org.person_clearance pc
             join registry.classification cleared on cleared.id = pc.max_classification
            where pc.subject_id = p_person
              and pc.organization_id = p_organization
              and pc.valid_from <= now()
              and (pc.valid_to is null or pc.valid_to > now())
              and not exists (select 1 from org.person_clearance_retirement r
                               where r.clearance_id = pc.id)
              and cleared.rank >= (select rank from rank))
     and exists (
           select 1
             from org.effective_access_grant g
             left join registry.classification ceiling on ceiling.id = g.classification_ceiling
            where g.organization_id = p_organization
              and g.capability = 'read'
              and g.scope_object_id in (p_organization, p_object)
              and g.valid_from <= now()
              and (g.valid_to is null or g.valid_to > now())
              and (g.classification_ceiling is null or ceiling.rank >= (select rank from rank))
              and ((g.principal_kind = 'person' and g.principal_id = p_person)
                or (g.principal_kind = 'role_assignment' and exists (
                      select 1 from org.role_assignment ra
                       where ra.id = g.principal_id and ra.subject_id = p_person
                         and ra.valid_from <= now()
                         and (ra.valid_to is null or ra.valid_to > now())))))
$$;

revoke all on function core.notification_person_reads(uuid, uuid, uuid, text) from public;

-- Whether a classification may leave the host under an organization's ceiling.
create function core.may_leave_host(p_organization uuid, p_classification text) returns boolean
language sql
stable
security definer
set search_path = pg_catalog, core, registry
as $$
  select coalesce(
    (select c.rank <= ceiling.rank
       from registry.classification c, registry.classification ceiling
      where c.id = p_classification
        and ceiling.id = core.provider_ceiling_in_force(p_organization)),
    false)
$$;

revoke all on function core.may_leave_host(uuid, text) from public;

-- Every person's Needs you, redacted for a channel the deployment does not control. One row per
-- item. `disclosed` false: no identifier and no title, only that an item of `kind` exists.
--
--   to_verify       unverified records an agent wrote, created by someone else, which the person
--                   reads and may verify (a live technical_authority assignment at the
--                   organization or the record) — the toVerify list of GET /needs-you;
--   awaiting_others unverified records an agent wrote for this person;
--   proposal        institutional acts the person's agents proposed, unanswered. Disclosed as the
--                   act's name and its targets' titles only when every target may leave the host
--                   and the person reads it; the payload and reason are never returned.
--
-- People with no e-mail address, no live assignment in the organization, or the digest turned off
-- are not listed.
create function core.needs_you_digest()
returns table (
  organization_id uuid,
  organization_name text,
  person_id uuid,
  email text,
  kind text,
  disclosed boolean,
  item_id uuid,
  title text
)
language sql
stable
security definer
set search_path = pg_catalog, core, org, registry
as $$
  with recipients as (
    select distinct ra_object.organization_id, p.id as person_id, btrim(p.email) as email
      from org.person p
      join org.role_assignment ra on ra.subject_id = p.id
      join core.object ra_object on ra_object.id = ra.id
     where p.email is not null and p.email ~ '^[^@\s<>]+@[^@\s<>]+$'
       and ra.valid_from <= now() and (ra.valid_to is null or ra.valid_to > now())
       and coalesce(
             (select np.digest from core.notification_preference np
               where np.organization_id = ra_object.organization_id and np.person_id = p.id
               order by np.revision desc limit 1),
             'daily') = 'daily'
  ),
  touched as (
    select distinct on (t.id) t.id, a.organization_id, a.actor_id
      from core.action a
     cross join lateral unnest(a.target_ids) as t(id)
     where a.agent_participation is not null
       and a.action_type not in ('propose_act', 'set_verification_policy',
                                 'resolve_act_proposal', 'compile_master_record')
     order by t.id, a.recorded_at desc
  ),
  unverified as (
    select o.id, o.organization_id, o.classification, o.title, o.created_by
      from touched
      join core.object o on o.id = touched.id and o.organization_id = touched.organization_id
     where o.object_type <> 'organization'
       and not exists (select 1 from core.object_verification v where v.object_id = o.id)
  ),
  record_items as (
    select r.organization_id, r.person_id, r.email,
           case when u.created_by = r.person_id then 'awaiting_others' else 'to_verify' end as kind,
           u.id, u.classification, u.title
      from recipients r
      join unverified u on u.organization_id = r.organization_id
     where core.notification_person_reads(r.person_id, r.organization_id, u.id, u.classification)
       and (u.created_by = r.person_id
            or exists (select 1 from org.role_assignment ra
                         join core.object ra_object on ra_object.id = ra.id
                        where ra.subject_id = r.person_id
                          and ra_object.organization_id = r.organization_id
                          and ra.role_id = 'technical_authority'
                          and ra.scope_id in (r.organization_id, u.id)
                          and ra.valid_from <= now()
                          and (ra.valid_to is null or ra.valid_to > now())))
  ),
  proposal_items as (
    select r.organization_id, r.person_id, r.email, 'proposal'::text as kind, p.id,
           p.action_type,
           (select bool_and(core.may_leave_host(r.organization_id, o.classification)
                            and core.notification_person_reads(r.person_id, r.organization_id,
                                                               o.id, o.classification))
              from core.object o where o.id = any(p.target_ids)) as targets_leave,
           (select string_agg(o.title, '; ' order by o.title)
              from core.object o where o.id = any(p.target_ids)) as target_titles
      from recipients r
      join core.act_proposal p
        on p.organization_id = r.organization_id and p.proposed_for = r.person_id
     where not exists (select 1 from core.act_proposal_resolution x where x.proposal_id = p.id)
  ),
  -- The organization's legal name, under the same rule as any record's title: it is a field of the
  -- organization's own record.
  organization_names as (
    select o.id,
           case when core.may_leave_host(o.id, org_object.classification) then o.legal_name end
             as name
      from org.organization o
      join core.object org_object on org_object.id = o.id
  )
  select i.organization_id, n.name, i.person_id, i.email, i.kind,
         core.may_leave_host(i.organization_id, i.classification),
         case when core.may_leave_host(i.organization_id, i.classification) then i.id end,
         case when core.may_leave_host(i.organization_id, i.classification) then i.title end
    from record_items i
    join organization_names n on n.id = i.organization_id
  union all
  select i.organization_id, n.name, i.person_id, i.email, i.kind,
         coalesce(i.targets_leave, false),
         case when coalesce(i.targets_leave, false) then i.id end,
         case when coalesce(i.targets_leave, false)
              then i.action_type || coalesce(': ' || i.target_titles, '') end
    from proposal_items i
    join organization_names n on n.id = i.organization_id
$$;

revoke all on function core.needs_you_digest() from public;
grant execute on function core.needs_you_digest() to kf_notifier;

-- The urgent items that arose after `p_since`, one row per item and person to tell, and nothing
-- about the item but its kind: a push names no record, no person and no organization.
--
--   proposal_waiting  an institutional act an agent proposed for this person, waiting on them;
--   blocker_opened    a warrant blocker opened in the organization, for each person holding a live
--                     organization-wide technical_authority assignment there: a person is blocked
--                     on the organization, and the organization's authority is who can unblock.
--
-- A failed backup or alert is the third urgent kind; it is pushed by kf-alert@.service, the path
-- every unit's OnFailure= already takes, and is not repeated here.
create function core.urgent_notifications(p_since timestamptz)
returns table (person_id uuid, kind text, arose_at timestamptz)
language sql
stable
security definer
set search_path = pg_catalog, core, org, work
as $$
  select p.proposed_for, 'proposal_waiting'::text, p.proposed_at
    from core.act_proposal p
   -- Compared at millisecond precision: the notifier keeps its boundary as a JavaScript instant.
   where date_trunc('milliseconds', p.proposed_at) > p_since
     and not exists (select 1 from core.act_proposal_resolution x where x.proposal_id = p.id)
     and coalesce(
           (select np.push from core.notification_preference np
             where np.organization_id = p.organization_id and np.person_id = p.proposed_for
             order by np.revision desc limit 1),
           'urgent') = 'urgent'
  union all
  select ra.subject_id, 'blocker_opened'::text, b.opened_at
    from work.warrant_blocker b
    join core.object warrant_object on warrant_object.id = b.warrant_id
    join org.role_assignment ra
      on ra.role_id = 'technical_authority'
     and ra.scope_id = warrant_object.organization_id
     and ra.valid_from <= now() and (ra.valid_to is null or ra.valid_to > now())
   where date_trunc('milliseconds', b.opened_at) > p_since
     and b.resolved_at is null
     and coalesce(
           (select np.push from core.notification_preference np
             where np.organization_id = warrant_object.organization_id
               and np.person_id = ra.subject_id
             order by np.revision desc limit 1),
           'urgent') = 'urgent'
$$;

revoke all on function core.urgent_notifications(timestamptz) from public;
grant execute on function core.urgent_notifications(timestamptz) to kf_notifier;

-- 4. The guards every new table inherits --------------------------------------------------------

insert into content.master_record_input_exemption (table_name, reason) values
  ('core.model_routing_policy',
   'What may leave the host, per organization; read when an answer is routed, never by a '
   'permitted-set read.'),
  ('core.notification_preference',
   'A person''s own notification setting; read by the notifier''s functions, never by a '
   'permitted-set enumeration.');

-- Every row kf_app writes here belongs to an act recorded in this transaction (20260925011000).
select core.install_action_context_guards();

-- migrate:down

drop trigger if exists zz_written_under_an_act on core.model_routing_policy;
drop trigger if exists written_act_is_recorded on core.model_routing_policy;
drop trigger if exists zz_written_under_an_act on core.notification_preference;
drop trigger if exists written_act_is_recorded on core.notification_preference;

delete from content.master_record_input_exemption
 where table_name in ('core.model_routing_policy', 'core.notification_preference');

drop function core.urgent_notifications(timestamptz);
drop function core.needs_you_digest();
drop function core.may_leave_host(uuid, text);
drop function core.notification_person_reads(uuid, uuid, uuid, text);

drop table core.notification_preference;
drop function core.notification_preference_bounded();

drop table core.model_routing_policy;
drop function core.model_routing_policy_bounded();
drop function core.provider_ceiling_in_force(uuid);

revoke usage on schema core from kf_notifier;
-- The role stays: a login may still inherit it, and roles are cluster-wide, not this database's.
