/**
 * A release tree must not depend on anything outside itself, and the verifier must SAY SO.
 *
 * Both halves of this file come from the first real host install, on 2026-08-26, and each was
 * invisible until then.
 *
 * THE RELEASE. `pnpm deploy --legacy` writes workspace links whose relative depth only holds
 * inside this monorepo:
 *
 *   packages/operations/node_modules/@kf/database -> ../../../../../../packages/database
 *
 * Six levels up from a release unpacked at `/opt/kf/knowledge-fabric-<id>/` is
 * `/opt/packages/database`, which does not exist — and the package's code was never copied in,
 * so the dangling link was the only reference to it. Every process importing a workspace
 * package died at startup on the host, `kf-commissioning` among them. The fix is
 * `injectWorkspacePackages: true` plus a plain `--prod` deploy, and these assertions exist so
 * that neither half can be quietly undone.
 *
 * THE VERIFIER. `migrate-release.sh check` detects the escape correctly and reported NOTHING,
 * because `readlink -f` fails on a path whose parents are absent and `set -e` ended the script
 * one line before the `case` that would have explained it. A guard that exits 1 in silence is
 * only marginally better than no guard: the operator learns that something is wrong and
 * nothing about what. That is guarded here by building a release with a deliberate escape and
 * requiring a NAMED refusal, not merely a nonzero status.
 *
 * WHAT THIS DOES NOT DO: build a real release. That takes minutes and a disposable worktree.
 * It checks the two settings that decide self-containment, and it exercises the verifier
 * against a purpose-built fixture, which is where the silence lived.
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';

const ROOT = join(import.meta.dirname, '..', '..');
const VERIFIER = join(ROOT, 'scripts', 'deploy', 'migrate-release.sh');
const made: string[] = [];

afterAll(() => {
  for (const dir of made) rmSync(dir, { recursive: true, force: true });
});

describe('the release recipe produces a self-contained tree', () => {
  it('sets injectWorkspacePackages, so workspace deps are copied rather than linked out', () => {
    const workspace = readFileSync(join(ROOT, 'pnpm-workspace.yaml'), 'utf8');
    expect(
      /^injectWorkspacePackages:\s*true\s*$/m.test(workspace),
      'pnpm-workspace.yaml no longer injects workspace packages. Without it `pnpm deploy` ' +
        'links workspace dependencies back into this monorepo by relative path, and the ' +
        'release stops working the moment it is unpacked anywhere else.',
    ).toBe(true);
  });

  it('does not deploy with --legacy, which is what produced the escaping links', () => {
    const document = readFileSync(join(ROOT, 'docs', 'deployment', 'private-host.md'), 'utf8');
    const legacy = document
      .split('\n')
      .filter((line) => /^pnpm .*\bdeploy\b/.test(line) && line.includes('--legacy'));
    expect(
      legacy,
      'the release recipe deploys with --legacy again. That flag writes workspace symlinks ' +
        'that escape the release root; see the note above these commands in private-host.md.',
    ).toEqual([]);
  });
});

describe('the release verifier names what it refuses', () => {
  /** Minimal release tree the verifier will walk, with one deliberately escaping symlink. */
  function releaseWithEscape(): string {
    const root = mkdtempSync(join(tmpdir(), 'kf-escape-'));
    made.push(root);
    // The verifier runs a series of preconditions before it reaches the symlink walk, so the
    // fixture has to be a plausible release and not only the one thing under test.
    mkdirSync(join(root, 'database', 'migrations'), { recursive: true });
    writeFileSync(
      join(root, 'database', 'migrations', '20260101000000_fixture.sql'),
      '-- migrate:up\nselect 1;\n-- migrate:down\nselect 1;\n',
    );
    mkdirSync(join(root, 'generated', 'sql-registry'), { recursive: true });
    writeFileSync(join(root, 'generated', 'sql-registry', '001-ontology-seed.sql'), 'select 1;\n');
    mkdirSync(join(root, 'nested'), { recursive: true });
    writeFileSync(join(root, 'nested', 'real.txt'), 'content\n');
    // Points far above the release root at a path that does not exist — exactly the shape
    // `pnpm deploy --legacy` emitted, and the shape that used to end the script in silence.
    symlinkSync('../../../../../../nowhere/at/all', join(root, 'nested', 'escapes'));

    // Generated by the same commands the seal step in private-host.md uses, so the three
    // inventories agree with the tree by construction rather than by my transcription.
    execFileSync(
      'bash',
      [
        '-c',
        [
          'set -e',
          'cd "$1"',
          "find -P . -mindepth 1 -type d -printf '%P\\n' | LC_ALL=C sort > DIRECTORIES",
          "find -P . -type l -printf '%P\\t%l\\n' | LC_ALL=C sort > SYMLINKS",
          "find -P . -type f ! -path ./SHA256SUMS -printf '%P\\0' | LC_ALL=C sort -z" +
            ' | xargs -0 sha256sum > SHA256SUMS',
        ].join('\n'),
        'bash',
        root,
      ],
      { stdio: ['ignore', 'pipe', 'pipe'] },
    );
    chmodSync(root, 0o755);
    return root;
  }

  it('refuses an escaping symlink WITH a message, not just a nonzero exit', () => {
    const root = releaseWithEscape();
    let status = 0;
    let output: string;
    try {
      output = execFileSync('bash', [VERIFIER, 'check', root], {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
        env: {
          ...process.env,
          KF_EXPECTED_RELEASE_OWNER_UID: String(process.getuid?.() ?? 0),
          KF_EXPECTED_RELEASE_MANIFEST_SHA256: createHash('sha256')
            .update(readFileSync(join(root, 'SHA256SUMS')))
            .digest('hex'),
        },
      });
    } catch (error) {
      const failure = error as { status?: number; stdout?: string; stderr?: string };
      status = failure.status ?? 1;
      output = `${failure.stdout ?? ''}${failure.stderr ?? ''}`;
    }

    expect(status, 'the verifier accepted a release with an escaping symlink').not.toBe(0);
    // The point of the test. It used to fail exactly like this and print nothing at all.
    expect(
      output.trim(),
      'the verifier refused the release and said nothing. An operator gets exit 1 and no ' +
        'cause, which is what happened on the first real host install.',
    ).not.toEqual('');
    expect(
      output,
      'the refusal does not name the offending link, so the operator cannot find it',
    ).toContain('nested/escapes');
  });
});
