#!/usr/bin/env bash
# Put `kf` on PATH.
#
# The CLI is declared as a bin in apps/api/package.json and that declaration does nothing until
# something links it. Until 2026-09-10 the command was only ever demonstrated as
# `node apps/api/dist/cli.js`, which is not the same thing as a command a person can run.
#
# The wrapper pins KF_ROOT to this checkout, so `kf` works from any directory rather than
# assuming the shell is sitting in the repository.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="${KF_BIN_DIR:-$HOME/.local/bin}"
entry="$root/apps/api/dist/cli.js"

test -f "$entry" || {
  echo "no build at $entry — run 'pnpm --filter @kf/api run build' first" >&2
  exit 1
}
mkdir -p "$target"

cat > "$target/kf" <<WRAPPER
#!/usr/bin/env bash
# Generated by scripts/install-kf.sh. Regenerate rather than edit.
exec env KF_ROOT="$root" node "$entry" "\$@"
WRAPPER
chmod 0755 "$target/kf"

echo "installed $target/kf -> $entry"
case ":$PATH:" in
  *":$target:"*) ;;
  *) echo "warning: $target is not on PATH; add it to your shell profile" >&2 ;;
esac
