#!/usr/bin/env node
/**
 * Derive the repository's perishable counts, so no document has to state one.
 *
 * The specification used to write these numbers into prose. They rotted: it claimed 88
 * migrations against 91, 168 tables against 174, 438 policies against 463, and the same wrong
 * figures had been copied into the dogfood host document and into a Warrant's compilation basis,
 * where each rotted independently. A disclaimer saying counts are perishable did not prevent any
 * of it; it only meant nobody was surprised.
 *
 * Transclusion into the specification would have been the obvious repair and is the wrong one.
 * §94.2 digests that document's exact bytes and acceptance freezes the digest, so substituting a
 * count at build time would break an accepted revision every time a migration landed. A signed
 * artifact cannot be a generated one. So the numbers live here, the specification cites this file
 * rather than quoting it, and the specification's bytes never move for a reason that is not a
 * decision.
 *
 * SOURCE COUNTS ONLY. A runtime count — how many tables a live database forces row-level security
 * on — cannot be derived from a checkout, and §103.3 keeps that distinction. Those stay in prose
 * with their measurement date and host, because there is nothing here that could check them.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();

function walk(dir, predicate, found = []) {
  for (const entry of readdirSync(join(ROOT, dir), { withFileTypes: true })) {
    const rel = `${dir}/${entry.name}`;
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '.next' || entry.name === 'dist')
        continue;
      walk(rel, predicate, found);
    } else if (predicate(entry.name, rel)) found.push(rel);
  }
  return found;
}

const migrations = walk('database/migrations', (name) => name.endsWith('.sql')).sort();

/**
 * Statements in the migrations' UP sections only, with SQL comments removed.
 *
 * The per-file truncation is the whole method and §103.3 records why. Every `drop table`
 * statement in this repository is in a down-section, so a count that reads whole files reports
 * a schema that is created and then destroyed. Truncating the concatenation instead of each
 * file is worse and quieter: the first down-marker ends the stream and every count after it
 * reads zero, which looks like a finding rather than a mistake.
 *
 * Comments are removed because the migrations explain themselves at length, and the
 * explanations name the constructs they explain. Counting `security definer` over raw text
 * included 29 comment lines saying why a function is or is not one, which inflated that measure
 * by a fifth. String literals are kept: a `create policy` inside `execute format('…')` is a
 * real statement, counted once per literal although its loop may run it many times. So these
 * are LITERAL statements — a construct generated by a loop is under-counted, and a string that
 * merely mentions one is over-counted. The migrations are written so both are rare, and §38
 * requires the ones that matter for the boundary registry to be literal.
 */
const withoutComments = (sql) => sql.replace(/--[^\n]*/g, '');
const upSections = migrations.map((file) => {
  const source = readFileSync(join(ROOT, file), 'utf8');
  const down = source.indexOf('-- migrate:down');
  return withoutComments(down === -1 ? source : source.slice(0, down));
});

const countStatements = (pattern) =>
  upSections.reduce((total, section) => total + (section.match(pattern)?.length ?? 0), 0);

/** Distinct names captured by the pattern's first group, case-folded. */
const distinctNames = (pattern) => {
  const names = new Set();
  for (const section of upSections)
    for (const match of section.matchAll(pattern)) names.add(match[1].toLowerCase());
  return names.size;
};

/**
 * Migrations that declare themselves irreversible. The marker is read from the down-section,
 * where `scripts/deploy/migrate-release.sh` reads it and where
 * `tests/deployment/migration-reversibility.test.ts` requires it on every empty down-section.
 */
const forwardOnly = migrations.filter((file) =>
  /^-- kf:forward-only \S/m.test(readFileSync(join(ROOT, file), 'utf8')),
).length;

const units = readdirSync(join(ROOT, 'deploy/systemd'));
const workspaceMembers = (dir) =>
  readdirSync(join(ROOT, dir), { withFileTypes: true }).filter(
    (entry) => entry.isDirectory() && existsSync(join(ROOT, dir, entry.name, 'package.json')),
  ).length;

// The records are OpenWarrant ADR atoms (`docs/decisions/atoms/`); the numbered files beside them
// are links kept so that every citation of the old path, signed ones included, still resolves.
const decisions = walk('docs/decisions/atoms', (name) => /^KF-ADR-\d{4}-.*\.md$/.test(name)).sort();
const decisionStatus = decisions.map((file) => {
  const source = readFileSync(join(ROOT, file), 'utf8');
  // The atom's frontmatter is the status of record; its body may discuss what was proposed.
  const status = /^---\n[\s\S]*?^status:\s*(\S+)\s*$[\s\S]*?^---$/m.exec(source)?.[1];
  if (status === undefined) throw new Error(`${file}: no status in the atom's frontmatter`);
  return status;
});

/**
 * Entries in one ontology document.
 *
 * Counted as top-level list items rather than by looking for `id:`, because the documents do not
 * agree on style: `action-types.yaml` writes `- id: create_initiative` and `relation-types.yaml`
 * writes `- { id: contains, ... }`. A pattern keyed on `id:` matched the first and silently
 * returned zero for the second — a wrong answer that reads like an empty file.
 */
const ontology = (file) => {
  const source = readFileSync(join(ROOT, `ontology/${file}`), 'utf8');
  return (source.match(/^ {2}- /gm) ?? []).length;
};

const sas = readFileSync(join(ROOT, 'docs/sas/KF_Software_Architecture_Specification.md'), 'utf8');

const measures = [
  ['migrations', migrations.length, 'files under `database/migrations/`'],
  [
    'forward-only migrations',
    forwardOnly,
    'migrations declaring `-- kf:forward-only <reason>` in their down-section',
  ],
  [
    'schemas',
    distinctNames(/create\s+schema\s+(?:if\s+not\s+exists\s+)?([a-z_]+)/gi),
    'distinct `create schema` names in migration up-sections',
  ],
  ['tables created', countStatements(/create table/gi), 'in migration up-sections'],
  ['row-security policies', countStatements(/create policy/gi), 'in migration up-sections'],
  [
    'triggers created',
    countStatements(/create\s+(?:or\s+replace\s+)?(?:constraint\s+)?trigger\b/gi),
    'literal `create trigger` statements in migration up-sections',
  ],
  [
    'security definer declarations',
    countStatements(/security definer/gi),
    'in migration up-sections; a function redefined is declared again',
  ],
  [
    'views',
    distinctNames(/create\s+(?:or\s+replace\s+)?(?:materialized\s+)?view\s+([a-z_.]+)/gi),
    'distinct view names in migration up-sections',
  ],
  [
    'indexes created',
    countStatements(/create\s+(?:unique\s+)?index\b/gi),
    'explicit `create index` statements in migration up-sections',
  ],
  [
    'foreign-key references',
    countStatements(/\breferences\s/gi),
    '`references` clauses in migration up-sections',
  ],
  [
    'check constraints',
    countStatements(/\bcheck\s*\(/gi),
    '`check (` clauses in migration up-sections',
  ],
  [
    'group roles',
    distinctNames(/create\s+role\s+([a-z_]+)\s+nologin/gi),
    'distinct `NOLOGIN` roles created in migration up-sections',
  ],
  [
    'workspace packages',
    workspaceMembers('packages') + workspaceMembers('apps'),
    `${workspaceMembers('packages')} libraries under \`packages/\`, ${workspaceMembers('apps')} executables under \`apps/\``,
  ],
  [
    'systemd services',
    units.filter((name) => name.endsWith('.service')).length,
    '`*.service` units under `deploy/systemd/`, the `kf-alert@` template counted once',
  ],
  [
    'systemd timers',
    units.filter((name) => name.endsWith('.timer')).length,
    '`*.timer` units under `deploy/systemd/`',
  ],
  ['action types', ontology('action-types.yaml'), 'declared in `ontology/action-types.yaml`'],
  ['object types', ontology('object-types.yaml'), 'declared in `ontology/object-types.yaml`'],
  ['relation types', ontology('relation-types.yaml'), 'declared in `ontology/relation-types.yaml`'],
  [
    'decision records',
    decisions.length,
    `atoms under \`docs/decisions/atoms/\` — ${[...new Set(decisionStatus)]
      .sort()
      .map((status) => `${decisionStatus.filter((s) => s === status).length} ${status}`)
      .join(', ')}`,
  ],
  [
    'architecture requirements',
    new Set(sas.match(/KF-SAS-RQ-\d{3,}/g) ?? []).size,
    'distinct identifiers in §106',
  ],
  [
    'test files',
    walk('tests', (name) => name.endsWith('.test.ts')).length +
      walk('apps', (name) => name.endsWith('.test.ts')).length +
      walk('packages', (name) => name.endsWith('.test.ts')).length,
    '`*.test.ts` under `tests/`, `apps/` and `packages/`',
  ],
];

/**
 * The newest latency run, as its own heading states it — read from the tracked file, never from a
 * live stack, so this build stays a function of the checkout.
 */
function latencyCitation() {
  const path = join(ROOT, 'generated/latency-bars.md');
  if (!existsSync(path)) return 'No run has been recorded.';
  const runs = readFileSync(path, 'utf8').match(/^## .+$/gmu) ?? [];
  if (runs.length === 0) return 'No run has been recorded.';
  const [newest] = runs;
  const commissioned = runs.filter((heading) => heading.endsWith('— commissioned')).length;
  return (
    `Newest run: \`${newest.slice(3)}\`; ${String(runs.length)} recorded, ` +
    `${String(commissioned)} from a commissioned host.` +
    (commissioned === 0 ? ' Every recorded run is a workstation run; none is official.' : '')
  );
}

const body = `<!-- GENERATED by scripts/measurements.mjs — do not hand-edit; the gate fails on drift. -->

# Measured counts

Derived from this checkout, every time the gate runs. No document states these numbers; documents
cite this file. A figure here cannot be stale without the build failing, which is the property the
prose version never had.

These are **source counts** in the sense of §103.3 — derived from the repository, and they move
when it moves. A **runtime count**, measured against a live database, cannot be derived from a
checkout and is not here; §38 and §40 carry those with their measurement date and host.

| Measure | Count | Derived from |
| --- | ---: | --- |
${measures.map(([name, count, from]) => `| ${name} | ${count} | ${from} |`).join('\n')}

## Runtime measurements, cited rather than derived

ADR 0024's latency bars (KF-SAS-RQ-201) are measured against a running stack by
\`scripts/latency-bars.mjs\`, which writes dated sections to
[\`generated/latency-bars.md\`](latency-bars.md). They are runtime figures, so this file only cites
them. ${latencyCitation()}
`;

/**
 * A zero is a broken derivation, not an empty repository.
 *
 * The relation-type count was zero on first run because the pattern did not match that file's
 * style, and it printed as a fact. Nothing downstream could have told it from the truth. This
 * repository has none of these things in zero quantity, so refusing is always the right answer
 * and a future measure that legitimately can be zero should say so here, deliberately.
 */
/** Measures that may legitimately read zero. Empty today; add a name here, never a bare `|| 0`. */
const MAY_BE_ZERO = new Set([]);

const empty = measures
  .filter(([name, count]) => count === 0 && !MAY_BE_ZERO.has(name))
  .map(([name]) => name);
if (empty.length > 0) {
  process.stderr.write(
    `refusing to write a measurement of zero for: ${empty.join(', ')}.\n` +
      'A zero here has always meant the derivation is broken, never that the repository is empty.\n' +
      'If one can legitimately be zero, name it in MAY_BE_ZERO rather than removing this check.\n',
  );
  process.exit(1);
}

writeFileSync(join(ROOT, 'generated/measurements.md'), body);
process.stdout.write(`generated/measurements.md — ${measures.length} measures\n`);
