/**
 * An archive written before a later migration added a column to a section that already existed
 * still restores, and restores that column as the migration gave rows that predated it (SAS
 * §100.32, KF-SAS-RQ-104, RQ-248).
 *
 * `deliverable-upconversion.test.ts` cuts old archives by removing SECTIONS. That leaves the other
 * half of an old archive's shape untested: the COLUMNS later migrations added to tables whose
 * sections it does carry. The importer inserts the columns a row names, so a missing column takes
 * the column default — right when the migration gave existing rows that default or left them
 * null, wrong when it backfilled something else or declared the column NOT NULL with no default.
 *
 * This file does two things:
 *
 *   1. Enumerates, from `database/migrations/`, every column added to an exported table by a
 *      migration after the one that created the table and after the format went to 2, and requires each to be classified below
 *      by what an archive without it restores as — exhaustively in both directions, so a new
 *      `add column` on an exported table fails here until somebody says what an older archive
 *      does with it.
 *   2. Exports a populated database, removes every reverted column whose section has rows,
 *      restores the result into a fresh database, exports again, and requires every file to come
 *      back as it went out except those columns — and those to hold their classified value.
 *
 * What it does not cover: a column added in a migration whose statement this parser does not read
 * (`alter table ... add column` is the only form the repository uses; a new spelling would be
 * missed, and the count assertion below is the check that the parse found anything); the
 * `label` and `upconverted` columns, whose old values are formats rather than defaults and are
 * restored by the importer under tests of their own; an archive lacking a column AND carrying
 * rows a later migration made possible (it restores every reverted column at once, which is a
 * superset of any one era's shape and not a reproduction of one); and sections the fixture leaves
 * empty, which carry no column names to revert — named in EMPTY_IN_FIXTURE so that list is checked
 * too.
 */

import { randomUUID, generateKeyPairSync } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { InMemoryObjectStore } from '@kf/artifacts';
import { canonicalize, digestBytes } from '@kf/canonicalization';
import { withTransaction } from '@kf/database';
import { createDocumentActionAtoms } from '@kf/documents';
import {
  createExport,
  EXPORT_MANIFEST_SIGNATURE_PATH,
  importExport,
  recomputeDatabaseSnapshotDigest,
  signExportPackage,
  verifyExport,
  type ExportManifest,
  type ExportPackage,
} from '@kf/export';
import { createFabricDispatcher } from '@kf/orchestrator';
import { IMPORT_TARGETS } from '../../packages/export/src/internal/import-targets.js';
import { seedFixtures, startHarness, type Fixtures, type Harness } from '../database/harness.js';

const ROOT = join(import.meta.dirname, '..', '..');
const MIGRATIONS = join(ROOT, 'database', 'migrations');
/**
 * The newest migration when the export format went to 2 (bffc6739, 2026-08-15). Every format-2
 * archive carries what the schema held then; a format-1 archive takes the importer's format-1
 * path (`tests/round-trip/export.test.ts`) and is not what this file is about.
 */
const FORMAT_2_LAST_MIGRATION = '20260815000200_ml_registry_bootstrap_actions.sql';

const KEY_ID = 'reverted-columns-key';
const KEY = generateKeyPairSync('ed25519');
const VERIFICATION = { trustedManifestKeys: new Map([[KEY_ID, KEY.publicKey]]) };

/** What a restore holds for a column the archive does not carry. */
type Restores =
  /** Generated by the database; never exported, so no archive carries it. */
  | { readonly kind: 'generated' }
  /** The migration left rows that predated it null, and the restore leaves them null. */
  | { readonly kind: 'null' }
  /**
   * The migration gave rows that predated it the column default, which the insert takes.
   * `notRoundTripped` says why a current row cannot be cut back to the old shape here.
   */
  | { readonly kind: 'default'; readonly exported: unknown; readonly notRoundTripped?: string }
  /** The migration computed it from the row; the importer computes it the same way. */
  | { readonly kind: 'derived' }
  /** The old value is a format label the importer supplies; tested where the label is. */
  | { readonly kind: 'label'; readonly testedBy: string }
  /** The old row has a different shape the importer converts; tested where that is. */
  | { readonly kind: 'upconverted'; readonly testedBy: string };

const NULL = { kind: 'null' } as const;
const GENERATED = { kind: 'generated' } as const;
const DELIVERABLES = {
  kind: 'upconverted',
  testedBy: 'tests/round-trip/deliverable-upconversion.test.ts',
} as const;

/** Every column added to an exported table after its creation, by section and column. */
const REVERTED_COLUMNS: Readonly<Record<string, Restores>> = {
  'objects.ns_head': GENERATED,
  'objects.ns_shape': GENERATED,
  'warrants.object_type': GENERATED,
  'ml-promotion-authority-decisions.object_type': GENERATED,
  'master-records.manifest_format': GENERATED,
  'role-assignments.classification_ceiling': NULL,
  'master-record-items.content_payload': {
    kind: 'default',
    exported: { $kf_type: 'postgres.jsonb', text: '{}' },
    // A record compiled before 20260826000500 has a manifest whose members carry no `content`,
    // so `{}` is exactly its payload. A current record's manifest does carry it, and the
    // importer refuses an item whose payload contradicts its manifest — a current record cut
    // back to the old item shape is a forgery, not an old archive.
    notRoundTripped: 'the fixture compiles a current record, whose manifest carries content',
  },
  'master-records.corpus_digest': { kind: 'derived' },
  'people.person_kind': { kind: 'default', exported: 'human' },
  'artifact-stores.public': { kind: 'default', exported: false },
  'document-publication-targets.public_store_id': NULL,
  'organizations.retired_at': NULL,
  'organizations.succeeded_by': NULL,
  'backup-copies.offsite_basis': NULL,
  'backup-copies.failure_domain_ref': NULL,
  'backup-copies.ciphertext_sha256': NULL,
  'audit-events.link_format': { kind: 'label', testedBy: 'tests/round-trip/export.test.ts' },
  'actions.agent_participation': NULL,
  'document-parses.digest_format': {
    kind: 'label',
    testedBy: 'packages/export/src/internal/importer/sections.ts withRecordedParseFormat',
  },
  'deliverables.work_order_id': DELIVERABLES,
  'deliverables.description': DELIVERABLES,
  'deliverables.acceptance_criteria': DELIVERABLES,
  'deliverables.due_date': DELIVERABLES,
  'artifact-stores.endpoint': NULL,
  'artifact-stores.bucket': NULL,
  'artifact-stores.bound_at': NULL,
  'backup-copies.provider_object': NULL,
  'object-verifications.policy_id': NULL,
};

/** Sections with reverted columns that this fixture leaves empty: nothing to revert in them. */
const EMPTY_IN_FIXTURE = ['backup-copies', 'document-publication-targets', 'object-verifications'];

/** `section.column` for every `add column` on an exported table after the table's creation. */
function addedColumns(): string[] {
  const sectionsOf = new Map<string, string[]>();
  for (const [section, table] of Object.entries(IMPORT_TARGETS)) {
    sectionsOf.set(table, [...(sectionsOf.get(table) ?? []), section]);
  }
  const files = readdirSync(MIGRATIONS)
    .filter((name) => name.endsWith('.sql'))
    .sort();
  const up = (name: string): string =>
    readFileSync(join(MIGRATIONS, name), 'utf8')
      .split('-- migrate:down')[0]!
      .replace(/--[^\n]*/g, '');
  const createdIn = new Map<string, string>();
  for (const name of files) {
    for (const match of up(name).matchAll(
      /create\s+table\s+(?:if\s+not\s+exists\s+)?([a-z_]+\.[a-z_0-9]+)/gi,
    )) {
      if (!createdIn.has(match[1]!)) createdIn.set(match[1]!, name);
    }
  }
  const found = new Set<string>();
  for (const name of files) {
    for (const statement of up(name).matchAll(
      /alter\s+table\s+(?:if\s+exists\s+)?(?:only\s+)?([a-z_]+\.[a-z_0-9]+)\s+([\s\S]*?);/gi,
    )) {
      const table = statement[1]!;
      const created = createdIn.get(table);
      if (created === undefined || created >= name || name <= FORMAT_2_LAST_MIGRATION) continue;
      for (const column of statement[2]!.matchAll(
        /add\s+column\s+(?:if\s+not\s+exists\s+)?([a-z_0-9]+)/gi,
      )) {
        for (const section of sectionsOf.get(table) ?? []) found.add(`${section}.${column[1]!}`);
      }
    }
  }
  return [...found].sort();
}

describe('every column added to an exported section is classified (SAS §100.32)', () => {
  it('finds the added columns at all (non-vacuous)', () => {
    expect(addedColumns().length).toBeGreaterThan(20);
    expect(addedColumns()).toContain('role-assignments.classification_ceiling');
  });

  it('classifies exactly the columns the migrations added, in both directions', () => {
    expect(addedColumns()).toEqual(Object.keys(REVERTED_COLUMNS).sort());
  });

  it('would report a planted add column on an exported table', () => {
    // The enumeration is what makes the table exhaustive; a parse that found nothing new would
    // pass the equality above vacuously after the next migration. Plant one in memory.
    const planted = [...addedColumns(), 'people.planted_column'].sort();
    expect(planted).not.toEqual(Object.keys(REVERTED_COLUMNS).sort());
  });
});

let h: Harness;
let f: Fixtures;
let pkg: ExportPackage;

type JsonRow = Record<string, unknown>;

function rowsOf(p: ExportPackage, name: string): JsonRow[] {
  const file = p.files.find((entry) => entry.path === `${name}.json`);
  if (file === undefined) throw new Error(`export has no ${name}.json`);
  return JSON.parse(file.content) as JsonRow[];
}

function sign(p: ExportPackage): ExportPackage {
  return signExportPackage(p, { keyId: KEY_ID, privateKey: KEY.privateKey });
}

/** Rewrite some sections' rows and sign again; the result must verify. */
function repack(base: ExportPackage, changes: ReadonlyMap<string, JsonRow[]>): ExportPackage {
  const files = base.files
    .filter((x) => x.path !== 'manifest.json' && x.path !== EXPORT_MANIFEST_SIGNATURE_PATH)
    .map((x) =>
      changes.has(x.path) ? { path: x.path, content: `${canonicalize(changes.get(x.path))}\n` } : x,
    );
  const manifest: ExportManifest = {
    ...base.manifest,
    database_snapshot_sha256: recomputeDatabaseSnapshotDigest(files, new Set()),
    files: files.map((file) => {
      const bytes = Buffer.from(file.content, 'utf8');
      return { path: file.path, size_bytes: bytes.length, sha256: digestBytes(bytes) };
    }),
  };
  const result = sign({
    files: [...files, { path: 'manifest.json', content: `${canonicalize(manifest)}\n` }],
    manifest,
  });
  expect(verifyExport(result, VERIFICATION)).toEqual([]);
  return result;
}

/** The columns this round trip removes: exported, not a label or a shape, by section. */
function revertible(): Map<string, string[]> {
  const out = new Map<string, string[]>();
  for (const [key, restores] of Object.entries(REVERTED_COLUMNS)) {
    if (!['null', 'default', 'derived'].includes(restores.kind)) continue;
    if (restores.kind === 'default' && restores.notRoundTripped !== undefined) continue;
    const [section, column] = key.split('.') as [string, string];
    out.set(section, [...(out.get(section) ?? []), column]);
  }
  return out;
}

beforeAll(async () => {
  h = await startHarness();
  f = await seedFixtures(h.adminPool);
  const execute = createFabricDispatcher(
    h.pool,
    createDocumentActionAtoms({
      store: new InMemoryObjectStore(),
      parser: {
        async parse() {
          return undefined;
        },
      },
    }),
  );
  // A master record and its items, so the derived corpus digest and the defaulted content
  // payload are exercised against rows rather than an empty section.
  await execute({
    actionType: 'compile_master_record',
    actorId: f.performerId,
    actingRoleId: f.performerRoleId,
    organizationId: f.organizationId,
    maxClassification: 'restricted',
    targetIds: [f.performerId],
    idempotencyKey: randomUUID(),
  });
  pkg = sign(await withTransaction(h.adminPool, (tx) => createExport(tx)));
}, 240_000);

afterAll(async () => {
  await h?.stop();
});

describe('an archive without the columns later migrations added restores (SAS §100.32)', () => {
  it('exports every column it classifies as carried', () => {
    for (const [section, columns] of revertible()) {
      const rows = rowsOf(pkg, section);
      if (EMPTY_IN_FIXTURE.includes(section)) {
        expect(rows, `${section} is listed as empty in the fixture`).toEqual([]);
        continue;
      }
      expect(rows.length, `${section} has no rows to revert`).toBeGreaterThan(0);
      for (const column of columns) {
        expect(Object.keys(rows[0]!), `${section}.json does not carry ${column}`).toContain(column);
      }
    }
  });

  it('restores each as the migration left older rows, and everything else unchanged', async () => {
    const reverted = new Map<string, JsonRow[]>();
    for (const [section, columns] of revertible()) {
      if (EMPTY_IN_FIXTURE.includes(section)) continue;
      reverted.set(
        `${section}.json`,
        rowsOf(pkg, section).map((row) =>
          Object.fromEntries(Object.entries(row).filter(([column]) => !columns.includes(column))),
        ),
      );
    }
    const older = repack(pkg, reverted);
    for (const [path, rows] of reverted) {
      const section = path.replace(/\.json$/, '');
      for (const column of revertible().get(section)!) {
        expect(Object.keys(rows[0]!), `${section} still names ${column}`).not.toContain(column);
      }
    }

    const fresh = await startHarness();
    try {
      await withTransaction(fresh.adminPool, (tx) => importExport(tx, older, VERIFICATION));
      const again = sign(await withTransaction(fresh.adminPool, (tx) => createExport(tx)));
      expect(verifyExport(again, VERIFICATION)).toEqual([]);

      const expected = (section: string, row: JsonRow): JsonRow => {
        const out = { ...row };
        for (const column of revertible().get(section) ?? []) {
          const restores = REVERTED_COLUMNS[`${section}.${column}`]!;
          if (restores.kind === 'null') out[column] = null;
          if (restores.kind === 'default') out[column] = restores.exported;
          // `derived` keeps the value the archive's own exporter would have recorded.
        }
        return out;
      };
      for (const file of pkg.files) {
        if (file.path === 'manifest.json' || file.path === EXPORT_MANIFEST_SIGNATURE_PATH) continue;
        const section = file.path.replace(/\.json$/, '');
        const restored = again.files.find((entry) => entry.path === file.path);
        expect(restored, `${file.path} is missing after the restore`).toBeDefined();
        if (!revertible().has(section) || EMPTY_IN_FIXTURE.includes(section)) {
          expect(restored!.content, `${file.path} differs after the restore`).toBe(file.content);
          continue;
        }
        expect(
          rowsOf(again, section),
          `${section} did not restore its reverted columns as classified`,
        ).toEqual(rowsOf(pkg, section).map((row) => expected(section, row)));
      }
    } finally {
      await fresh.stop();
    }
  }, 300_000);
});
