import { createHash } from 'node:crypto';
import { join, posix } from 'node:path';
import { compareCanonicalText } from '@kf/canonicalization';
import type {
  LamQuantCompatibilityFileSystem,
  LamQuantNamedDigest,
  LamQuantSemanticProjection,
} from './contracts.js';
import { parseComposeProfile, reject, type ComposeParent } from './compose-profile.js';
import { parseFrontmatter, stringValue } from './frontmatter.js';
import { normalizeGeneratedMarkdown } from './normalize-markdown.js';
import {
  normalizeDocLink,
  readAtom,
  readLedger,
  readText as readSourceText,
  readTopics,
  type AtomRecord,
} from './source-contracts.js';

/** Parse compiler outputs and retained source files without accepting source-side expectations. */
export async function buildGeneratedSemanticProjection(
  root: string,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<LamQuantSemanticProjection> {
  const allDocs = await listDocs(root, fileSystem);
  const compose = parseComposeProfile(await readText(root, 'docs/compose.toml', fileSystem));
  const atoms = await readDeclaredAtoms(root, compose, fileSystem);
  const topicPages = await generatedTopicPages(root, allDocs, fileSystem);
  const parentOutputs = await generatedParents(root, allDocs, compose, fileSystem);
  return {
    atomMembership: declaredMembership(compose, atoms),
    parentOutputs,
    topics: topicPages.map((page) => page.slug).sort(compareCanonicalText),
    topicMembership: await generatedTopicMembership(root, topicPages, compose, atoms, fileSystem),
    ledgerBindings: await generatedLedgerBindings(root, compose, atoms, fileSystem),
    deprecations: generatedDeprecations(compose, atoms),
    adrInventory: await generatedAdrInventory(root, fileSystem),
    adrViews: await generatedAdrViews(root, fileSystem),
    traceability: await generatedTraceability(root, fileSystem),
    bookOrder: await readBookOrder(root, fileSystem),
  };
}

async function readDeclaredAtoms(
  root: string,
  parents: readonly ComposeParent[],
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<ReadonlyMap<string, AtomRecord>> {
  const atoms = new Map<string, AtomRecord>();
  for (const path of new Set(parents.flatMap((parent) => parent.atoms))) {
    atoms.set(path, await readAtom(root, path, fileSystem));
  }
  return atoms;
}

function declaredMembership(
  parents: readonly ComposeParent[],
  atoms: ReadonlyMap<string, AtomRecord>,
): readonly string[] {
  return sorted(
    parents.flatMap((parent) => {
      let ordinal = 0;
      return parent.atoms.flatMap((path): string[] => {
        const atom = atoms.get(path);
        if (atom === undefined) reject(`generated profile cannot read atom '${path}'`);
        return atom.deprecated ? [] : [record(parent.file, ordinal++, path)];
      });
    }),
  );
}

async function generatedParents(
  root: string,
  allDocs: readonly string[],
  compose: readonly ComposeParent[],
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly LamQuantNamedDigest[]> {
  const paths = new Set(compose.map((parent) => parent.file));
  for (const path of allDocs.filter((item) => item.endsWith('.md'))) {
    const text = await maybeRead(root, path, fileSystem);
    if (text === undefined) continue;
    const parsed = parseFrontmatter(text);
    if (
      stringValue(parsed.data.kind) === 'composite' ||
      /<!--\s*GENERATED by tools\/doc_compose\.py\b/i.test(text)
    ) {
      paths.add(path);
    }
  }
  const output: LamQuantNamedDigest[] = [];
  for (const path of [...paths].sort(compareCanonicalText)) {
    const text = await maybeRead(root, path, fileSystem);
    if (text !== undefined) {
      output.push({ path, sha256: digest(normalizeGeneratedMarkdown(text)) });
    }
  }
  return output;
}

interface TopicPage {
  readonly slug: string;
  readonly path: string;
}

async function generatedTopicPages(
  root: string,
  allDocs: readonly string[],
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly TopicPage[]> {
  const declared = await readTopics(root, fileSystem);
  const pages: TopicPage[] = [];
  for (const path of allDocs.filter(
    (item) => item.startsWith('docs/topics/') && item.endsWith('.md'),
  )) {
    const basename = posix.basename(path, '.md');
    if (basename === 'index' || basename === 'adr-index' || basename === 'adr-digest') continue;
    const text = await readText(root, path, fileSystem);
    const node = stringValue(parseFrontmatter(text).data.node);
    const nodeSlug = node?.startsWith('topic-') ? node.slice('topic-'.length) : undefined;
    if (!declared.has(basename) && nodeSlug === undefined) continue;
    const slug = nodeSlug ?? basename;
    if (slug !== basename) reject(`${path}: generated topic node does not match its path`);
    pages.push({ slug, path });
  }
  return pages.sort((left, right) => compareCanonicalText(left.slug, right.slug));
}

async function generatedTopicMembership(
  root: string,
  pages: readonly TopicPage[],
  parents: readonly ComposeParent[],
  atoms: ReadonlyMap<string, AtomRecord>,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly string[]> {
  const parentByPath = new Map(parents.map((parent) => [parent.file, parent]));
  const out: string[] = [];
  for (const page of pages) {
    const text = await readText(root, page.path, fileSystem);
    let currentParent: { title: string; path: string } | undefined;
    const consumedByParent = new Map<string, Set<string>>();
    for (const line of text.replace(/\r\n?/g, '\n').split('\n')) {
      const parent = /^### \[([^\]]+)]\(([^)]+)\)/.exec(line);
      if (parent !== null) {
        currentParent = {
          title: parent[1]!,
          path: normalizeTopicLink(page.path, parent[2]!),
        };
        out.push(record(page.slug, 'doc', currentParent.title, currentParent.path));
        continue;
      }
      const adr = /^- \[ADR (\d{4})\s*[—-]\s*([^\]]+)]\(([^)]+)\)/.exec(line);
      if (adr !== null) {
        out.push(
          record(
            page.slug,
            'adr',
            adr[1]!,
            adr[2]!.trim(),
            normalizeTopicLink(page.path, adr[3]!),
          ),
        );
        continue;
      }
      const atom = line.startsWith('- [') ? null : /^- (.+)$/.exec(line);
      if (atom === null || currentParent === undefined) continue;
      const title = atom[1]!.trim();
      const consumed = consumedByParent.get(currentParent.path) ?? new Set<string>();
      const declaredParent = parentByPath.get(currentParent.path);
      const matched = declaredParent?.atoms.find((path) => {
        const candidate = atoms.get(path);
        return (
          candidate !== undefined &&
          !candidate.deprecated &&
          candidate.title === title &&
          candidate.topics.includes(page.slug) &&
          !consumed.has(path)
        );
      });
      if (matched !== undefined) consumed.add(matched);
      consumedByParent.set(currentParent.path, consumed);
      out.push(record(page.slug, 'atom', title, currentParent.path, matched ?? null));
    }
  }
  return sorted(out);
}

async function generatedLedgerBindings(
  root: string,
  parents: readonly ComposeParent[],
  atoms: ReadonlyMap<string, AtomRecord>,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly string[]> {
  const ledger = await readLedger(root, fileSystem);
  const output: string[] = [];
  for (const path of new Set(parents.flatMap((parent) => parent.atoms))) {
    if (atoms.get(path)?.deprecated) continue;
    const text = await readSourceText(root, path, fileSystem);
    for (const match of text.matchAll(/\{\{ledger:([^}]+)}}/g)) {
      const id = match[1]!.trim();
      if (!ledger.has(id)) reject(`generated profile has unknown ledger binding '${id}' in '${path}'`);
      output.push(record(path, id));
    }
  }
  return sorted(output);
}

function generatedDeprecations(
  parents: readonly ComposeParent[],
  atoms: ReadonlyMap<string, AtomRecord>,
): readonly string[] {
  const owner = new Map<string, { parent: string; ordinal: number }>();
  for (const parent of parents) {
    parent.atoms.forEach((path, ordinal) => owner.set(path, { parent: parent.file, ordinal }));
  }
  return sorted(
    [...atoms.values()]
      .filter((atom) => atom.deprecated)
      .map((atom) => {
        const location = owner.get(atom.path);
        if (location === undefined) reject(`deprecated atom '${atom.path}' has no generated owner`);
        return record(
          atom.path,
          atom.sha256,
          location.parent,
          location.ordinal,
          atom.deprecatedOn ?? '',
          atom.supersededBy,
        );
      }),
  );
}

async function generatedAdrInventory(
  root: string,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly string[]> {
  const index = await readText(root, 'docs/topics/adr-index.md', fileSystem);
  const overview = await readText(root, 'docs/ADR_OVERVIEW.md', fileSystem);
  const overviewByNumber = overviewFacts(overview);
  let status = 'unknown';
  const inventory: string[] = [];
  for (const line of index.replace(/\r\n?/g, '\n').split('\n')) {
    if (line.startsWith('## ')) status = statusFromHeading(line);
    const cells = tableCells(line);
    if (cells.length < 3) continue;
    const link = /^\[(\d{4})]\(([^)]+)\)/.exec(cells[0] ?? '');
    if (link === null) continue;
    const number = link[1]!;
    const facts = overviewByNumber.get(number) ?? { gate: 'none', relations: '' };
    inventory.push(
      record(
        number,
        normalizeDocLink('docs/topics/adr-index.md', link[2]!),
        cells[1]!.trim(),
        status,
        facts.gate,
        facts.relations,
        backtickValues(cells[2]!).sort(compareCanonicalText),
      ),
    );
  }
  return sorted(inventory);
}

function overviewFacts(markdown: string): ReadonlyMap<string, { gate: string; relations: string }> {
  const facts = new Map<string, { gate: string; relations: string }>();
  for (const line of markdown.replace(/\r\n?/g, '\n').split('\n')) {
    const cells = tableCells(line);
    if (cells.length < 5) continue;
    const link = /^\[(\d{4})]\(/.exec(cells[0] ?? '');
    if (link === null) continue;
    const gateText = cells[3]!.trim();
    facts.set(link[1]!, {
      gate: gateText.includes('declared') ? 'declared' : gateText.includes('debt') ? 'debt' : 'none',
      relations: generatedRelations(cells[4]!),
    });
  }
  return facts;
}

async function generatedAdrViews(
  root: string,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly string[]> {
  const expected = [
    ['docs/ADR_OVERVIEW.md', '# ADR Overview'],
    ['docs/topics/adr-index.md', '# ADR index'],
    ['docs/topics/adr-digest.md', '# ADR digest'],
  ] as const;
  const output: string[] = [];
  for (const [path, heading] of expected) {
    const text = await maybeRead(root, path, fileSystem);
    if (text !== undefined && text.includes(heading)) output.push(path);
  }
  return output;
}

async function generatedTraceability(
  root: string,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly string[]> {
  const text = await readText(root, 'docs/TRACEABILITY_MATRIX.md', fileSystem);
  return sorted(
    text
      .replace(/\r\n?/g, '\n')
      .split('\n')
      .flatMap((line): string[] => {
        const cells = tableCells(line);
        if (cells.length !== 6 || cells[0] === 'Component' || /^-+$/.test(cells[0] ?? '')) return [];
        return [record(...cells.map((cell) => cell.trim() || '—'))];
      }),
  );
}

async function readBookOrder(
  root: string,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly string[]> {
  const text = (await maybeRead(root, 'docs/_dist/BOOK.md', fileSystem)) ?? '';
  return [...text.matchAll(/^- `(docs\/[^`]+)`$/gm)].map((match) => match[1]!);
}

function tableCells(line: string): readonly string[] {
  if (!line.trimStart().startsWith('|')) return [];
  const cells: string[] = [];
  let value = '';
  let escaped = false;
  for (const character of line.trim().replace(/^\||\|$/g, '')) {
    if (escaped) {
      value += character;
      escaped = false;
    } else if (character === '\\') {
      escaped = true;
      value += character;
    } else if (character === '|') {
      cells.push(value.trim());
      value = '';
    } else {
      value += character;
    }
  }
  cells.push(value.trim());
  return cells;
}

function statusFromHeading(heading: string): string {
  const value = heading.toLowerCase();
  if (value.includes('in progress')) return 'in-progress';
  if (value.includes('complete')) return 'complete';
  if (value.includes('accepted')) return 'accepted';
  if (value.includes('proposed')) return 'proposed';
  if (value.includes('falsified')) return 'falsified';
  if (value.includes('superseded')) return 'superseded';
  if (value.includes('deprecated')) return 'deprecated';
  if (value.includes('rejected')) return 'rejected';
  if (value.includes('withdrawn')) return 'withdrawn';
  return 'unknown';
}

function backtickValues(value: string): string[] {
  return [...value.matchAll(/`([^`]+)`/g)].map((match) => match[1]!);
}

function normalizeTopicLink(from: string, target: string): string {
  return posix.normalize(posix.join(posix.dirname(from), target.split('#')[0]!));
}

function generatedRelations(value: string): string {
  if (value.trim() === '' || value.includes('—')) return '';
  return value
    .split(/[;,]/)
    .map((item) => {
      const match = /(supersedes|superseded_by|amends|amended_by|extends)\s+(\d{4})/.exec(
        item.trim().replace('superseded by', 'superseded_by').replace('amended by', 'amended_by'),
      );
      return match === null ? item.trim() : `${match[1]}:${match[2]}`;
    })
    .filter(Boolean)
    .join(',');
}

async function readText(
  root: string,
  path: string,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<string> {
  const text = await maybeRead(root, path, fileSystem);
  if (text === undefined) reject(`required LamQuant output '${path}' is missing`);
  return text;
}

async function maybeRead(
  root: string,
  path: string,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<string | undefined> {
  return (await fileSystem.kind(join(root, path))) === 'file'
    ? (await fileSystem.readFile(join(root, path))).toString('utf8')
    : undefined;
}

async function listDocs(
  root: string,
  fileSystem: LamQuantCompatibilityFileSystem,
): Promise<readonly string[]> {
  return (await fileSystem.listFiles(join(root, 'docs'))).map((path) => `docs/${path}`);
}

function digest(text: string): string {
  return createHash('sha256').update(text).digest('hex');
}

function record(...fields: readonly unknown[]): string {
  return JSON.stringify(fields);
}

function sorted(values: readonly string[]): readonly string[] {
  return [...values].sort(compareCanonicalText);
}
