/**
 * Order matters on the way back in: a row cannot reference a row that does not exist yet.
 * Objects before everything, people before role assignments, actions before audit events.
 */
export const IMPORT_ORDER = [
  'objects',
  // Seeded reference rows are reconciled before this loop, then restored from the package.
  'roles',
  'organizations',
  'people',
  'engagements',
  'role-assignments',
  'external-identities',
  'project-memberships',
  'actions',
  'person-clearances',
  'person-clearance-retirements',
  'legacy-action-provenance',
  'relations',
  'approvals',
  'snapshots',
  'audit-events',
  'audit-checkpoints',
  'outbox-events',
  'retention-holds',
  'person-entitlement-exclusions',
  'access-grants',
  'artifacts',
  'artifact-versions',
  'artifact-stores',
  'artifact-locations',
  'artifact-relationships',
  'external-identifiers',
  'document-parses',
  'document-atoms',
  'recovery-objectives',
  'backup-runs',
  'backup-copies',
  'restore-drills',
  'physical-failure-domain-evidence',
  'encrypted-backup-evidence',
  'initiative-projects',
  'milestones',
  'project-events',
  'work-packages',
  'work-orders',
  'work-order-scopes',
  'work-order-amendments',
  'deliverables',
  'work-executions',
  'deliverable-submissions',
  'acceptance-records',
  'acceptance-items',
  'invoices',
  'invoice-lines',
  'payments',
  'payment-allocations',
  'configuration-items',
  'interface-contracts',
  'interface-conformances',
  'physical-bindings',
  'baseline-items',
  'release-items',
  'effectivities',
  'federated-sources',
  'federated-references',
  'federated-links',
  'controlled-documents',
  'nonconformities',
  'capas',
  'capa-nonconformities',
  'suppliers',
  'supplier-qualifications',
  'equipment',
  'calibrations',
  'complaints',
  'training-requirements',
  'training-records',
  'decision-alternatives',
  'change-items',
  'risk-controls',
  'test-definitions',
  'test-executions',
  'test-execution-equipment',
  'verification-links',
  // Subject and Holder form the schema's one deliberately deferred table cycle. Subject first
  // keeps the Holder's ownership edge forward-facing; the reciprocal edge is satisfied once
  // both sections have restored.
  'document-subjects',
  'document-source-holders',
  'authored-fragments',
  'document-compositions',
  'authored-fragment-revisions',
  'composition-revisions',
  'typed-bindings',
  'document-compiler-registrations',
  'document-compiler-revocations',
  'compilation-bases',
  'compilation-basis-fragments',
  'compilation-basis-compositions',
  'compilation-basis-bindings',
  'compilation-runs',
  'compiled-views',
  'compilation-run-preimages',
  'document-publication-targets',
  'document-publication-target-retirements',
  'document-publications',
  'master-records',
  'master-record-items',
  'master-record-withholdings',
  'master-record-links',
  'master-record-link-revocations',
  'master-record-delivery-receipts',
  'master-record-link-access',
  // A generated-view input points at compiled_view, so inputs restore after run/view receipts.
  'composition-inputs',
  'proposal-overlays',
  'adr-decision-bodies',
  'ml-aggregate-references',
  'ml-run-lineages',
  'ml-run-lineage-inputs',
  'ml-run-lineage-outputs',
  'ml-run-lineage-parent-models',
  'ml-metric-definitions',
  'ml-metric-write-authorizations',
  'ml-metric-events',
  'ml-metric-segments',
  // Action provenance restores after every record kind it may bind.
  'ml-registry-registrations',
  // Run-seal verification material must exist before the signed seal that names it.
  'ml-run-seal-signing-keys',
  'ml-run-seals',
  // Restore withdrawal after the historical seal it deactivates.
  'ml-run-seal-signing-key-revocations',
  // Human authority binds core object/action/approval and aggregate evidence to this seal.
  'ml-promotion-authority-decisions',
  // Verification material must exist before the signed receipt history that names it.
  'ml-promotion-signing-keys',
  'ml-promotion-receipts',
  'ml-promotion-receipt-evidence',
  'ml-promotion-revocations',
  // Restore withdrawals last so historical receipts precede the event that deactivates a key.
  'ml-promotion-signing-key-revocations',
  'secure-object-authority-signing-keys',
  'secure-object-authority-signing-key-revocations',
  'secure-object-capability-requests',
  'secure-object-capability-issues',
  'secure-object-capability-revocations',
  'secure-object-capability-consumptions',
  'secure-object-erasure-requests',
  'secure-object-erasure-tombstones',
] as const;

// Format 1 is the original fixed 15-section package emitted before document compiler,
// operational evidence, ML, and secure-object ledgers joined the preservation boundary.
// Keep this list forever: treating missing v2 sections as optional under one version would
// make corruption indistinguishable from an old package.
export const LEGACY_V1_IMPORT_ORDER = [
  'objects',
  'organizations',
  'people',
  'engagements',
  'role-assignments',
  'actions',
  'relations',
  'approvals',
  'snapshots',
  'audit-events',
  'audit-checkpoints',
  'artifacts',
  'artifact-versions',
  'artifact-relationships',
  'external-identifiers',
] as const;
