/** Section name -> the table it restores into, for import. */
export const PRESERVATION_IMPORT_TARGETS = {
  objects: 'core.object',
  relations: 'core.relation',
  actions: 'core.action',
  'legacy-action-provenance': 'core.action_migration019_legacy',
  approvals: 'core.approval',
  snapshots: 'core.snapshot',
  'audit-events': 'core.audit_event',
  'audit-checkpoints': 'core.audit_checkpoint',
  organizations: 'org.organization',
  people: 'org.person',
  engagements: 'org.engagement',
  'role-assignments': 'org.role_assignment',
  'person-clearances': 'org.person_clearance',
  'person-clearance-retirements': 'org.person_clearance_retirement',
  'person-entitlement-exclusions': 'content.person_entitlement_exclusion',
  artifacts: 'content.artifact',
  'artifact-versions': 'content.artifact_version',
  'artifact-relationships': 'content.artifact_relationship',
  'external-identifiers': 'content.external_locator',
  'recovery-objectives': 'ops.recovery_objective',
  'backup-runs': 'ops.backup_run',
  'backup-copies': 'ops.backup_copy',
  'restore-drills': 'ops.restore_drill',
  'physical-failure-domain-evidence': 'ops.physical_failure_domain_evidence',
  'encrypted-backup-evidence': 'ops.encrypted_backup_evidence',
  'controlled-documents': 'quality.controlled_document',
  'document-subjects': 'content.document_subject',
  'document-source-holders': 'content.document_source_holder',
  'authored-fragments': 'content.authored_fragment',
  'document-compositions': 'content.document_composition',
  'authored-fragment-revisions': 'content.authored_fragment_revision',
  'composition-revisions': 'content.composition_revision',
  'typed-bindings': 'content.typed_binding',
  'document-compiler-registrations': 'content.document_compiler_registration',
  'document-compiler-revocations': 'content.document_compiler_revocation',
  'composition-inputs': 'content.composition_input',
  'compilation-bases': 'content.compilation_basis',
  'compilation-basis-fragments': 'content.compilation_basis_fragment',
  'compilation-basis-compositions': 'content.compilation_basis_composition',
  'compilation-basis-bindings': 'content.compilation_basis_binding',
  'compilation-runs': 'content.compilation_run',
  'compiled-views': 'content.compiled_view',
  'compilation-run-preimages': 'content.compilation_run_preimage',
  'document-publication-targets': 'content.document_publication_target',
  'document-publication-target-retirements': 'content.document_publication_target_retirement',
  'document-publications': 'content.document_publication',
  'master-records': 'content.master_record',
  'master-record-items': 'content.master_record_item',
  'master-record-withholdings': 'content.master_record_withholding',
  'master-record-links': 'content.master_record_link',
  'master-record-link-revocations': 'content.master_record_link_revocation',
  'master-record-delivery-receipts': 'content.master_record_delivery_receipt',
  'master-record-link-access': 'content.master_record_link_access',
  'proposal-overlays': 'content.proposal_overlay',
  'adr-decision-bodies': 'content.adr_decision_body',
  'ml-aggregate-references': 'ml.aggregate_reference',
  'ml-run-lineages': 'ml.run_lineage',
  'ml-run-lineage-inputs': 'ml.run_lineage_input',
  'ml-run-lineage-outputs': 'ml.run_lineage_output',
  'ml-run-lineage-parent-models': 'ml.run_lineage_parent_model',
  'ml-metric-definitions': 'ml.metric_definition',
  'ml-metric-write-authorizations': 'ml.metric_write_authorization',
  'ml-metric-events': 'ml.metric_event',
  'ml-metric-segments': 'ml.metric_segment',
  'ml-registry-registrations': 'ml.registry_registration',
  'ml-run-seal-signing-keys': 'ml.run_seal_signing_key',
  'ml-run-seals': 'ml.run_seal',
  'ml-run-seal-signing-key-revocations': 'ml.run_seal_signing_key_revocation',
  'ml-promotion-authority-decisions': 'ml.promotion_authority_decision',
  'ml-promotion-signing-keys': 'ml.promotion_signing_key',
  'ml-promotion-signing-key-revocations': 'ml.promotion_signing_key_revocation',
  'ml-promotion-receipts': 'ml.promotion_receipt',
  'ml-promotion-receipt-evidence': 'ml.promotion_receipt_evidence',
  'ml-promotion-revocations': 'ml.promotion_revocation',
  'secure-object-authority-signing-keys': 'secure_object.authority_signing_key',
  'secure-object-authority-signing-key-revocations':
    'secure_object.authority_signing_key_revocation',
  'secure-object-capability-requests': 'secure_object.capability_request',
  'secure-object-capability-issues': 'secure_object.capability_issue',
  'secure-object-capability-revocations': 'secure_object.capability_revocation',
  'secure-object-capability-consumptions': 'secure_object.capability_consumption',
  'secure-object-erasure-requests': 'secure_object.erasure_request',
  'secure-object-erasure-tombstones': 'secure_object.erasure_tombstone',
  'outbox-events': 'core.outbox',
  'retention-holds': 'core.retention_hold',
  roles: 'org.role',
  'external-identities': 'org.external_identity',
  'project-memberships': 'org.project_membership',
  'document-parses': 'content.document_parse',
  'document-atoms': 'content.document_atom',
  'initiative-projects': 'work.initiative_project',
  milestones: 'work.milestone',
  'project-events': 'work.project_event',
  'work-packages': 'work.work_package',
  'work-orders': 'work.work_order',
  'work-order-scopes': 'work.work_order_scope',
  'work-order-amendments': 'work.work_order_amendment',
  deliverables: 'work.deliverable',
  'work-executions': 'work.work_execution',
  'deliverable-submissions': 'work.deliverable_submission',
  'acceptance-records': 'work.acceptance_record',
  'acceptance-items': 'work.acceptance_item',
  invoices: 'finance.invoice',
  'invoice-lines': 'finance.invoice_line',
  payments: 'finance.payment',
  'payment-allocations': 'finance.payment_allocation',
  'configuration-items': 'product.configuration_item',
  'interface-contracts': 'product.interface_contract',
  'interface-conformances': 'product.interface_conformance',
  'physical-bindings': 'product.physical_binding',
  'baseline-items': 'product.baseline_item',
  'release-items': 'product.release_item',
  effectivities: 'product.effectivity',
  'decision-alternatives': 'engineering.decision_alternative',
  'change-items': 'engineering.change_item',
  'risk-controls': 'engineering.risk_control',
  'test-definitions': 'engineering.test_definition',
  'test-executions': 'engineering.test_execution',
  'test-execution-equipment': 'engineering.test_execution_equipment',
  'verification-links': 'engineering.verification_link',
  'federated-sources': 'quality.federated_source',
  'federated-references': 'quality.federated_reference',
  'federated-links': 'quality.federated_link',
  nonconformities: 'quality.nonconformity',
  capas: 'quality.capa',
  'capa-nonconformities': 'quality.capa_nonconformity',
  suppliers: 'quality.supplier',
  'supplier-qualifications': 'quality.supplier_qualification',
  equipment: 'quality.equipment',
  calibrations: 'quality.calibration',
  complaints: 'quality.complaint',
  'training-requirements': 'quality.training_requirement',
  'training-records': 'quality.training_record',
} as const satisfies Readonly<Record<string, string>>;

export const IMPORT_TARGETS: Readonly<Record<string, string>> = PRESERVATION_IMPORT_TARGETS;

/** Tables intentionally reconstructed or discarded rather than imported as authority. */
export const PRESERVATION_TABLE_EXCLUSIONS = {
  'registry.*': 'deterministic ontology seed carried in ontology/registry.json',
  'search.document': 'derived search projection rebuilt from authoritative records',
  'core.audit_chain_head': 'derived global append cursor rebuilt from verified audit history',
  'core.migration030_rollback_state': 'path-local migration rollback metadata, not authority',
  'content.compiler_runtime_lease': 'ephemeral worker lease, invalid after restore',
  'content.document_basis_classifier_lease': 'ephemeral classifier lease, invalid after restore',
} as const;
